

CREATE DATABASE IF NOT EXISTS leafcure
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE leafcure;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  joined_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  scan_count INT NOT NULL DEFAULT 0,
  diseased_count INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS scans (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  user_name VARCHAR(200) NOT NULL,
  email VARCHAR(255) NOT NULL,
  leaf_scanned VARCHAR(255) NOT NULL,
  diagnosis VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_scans_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
